services:
  db:
    image: mariadb:10.5
    container_name: workout-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workout
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: workout-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/workout
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  frontend:
    build:
      context: ./frontend
    container_name: workout-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  db_data: