spring.application.name=backend

spring.datasource.url=jdbc:mariadb://workout-db:3306/workout
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
