package com.workoutplanner.backend.service;

import com.workoutplanner.backend.model.Exercise;
import com.workoutplanner.backend.model.Routine;
import com.workoutplanner.backend.model.User;
import com.workoutplanner.backend.model.Workout;
import com.workoutplanner.backend.model.WorkoutExercise;
import com.workoutplanner.backend.repository.ExerciseRepository;
import com.workoutplanner.backend.repository.RoutineRepository;
import com.workoutplanner.backend.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.ArrayList;
import static org.springframework.http.HttpStatus.NOT_FOUND;
import static org.springframework.http.HttpStatus.BAD_REQUEST;

import java.util.List;

@Service
public class RoutineService {

    private final RoutineRepository repository;
    private final UserRepository userRepository;
    private final ExerciseRepository exerciseRepository;

    public RoutineService(RoutineRepository repository,
                          UserRepository userRepository,
                          ExerciseRepository exerciseRepository) {
        this.repository = repository;
        this.userRepository = userRepository;
        this.exerciseRepository = exerciseRepository;
    }

    // =========================
    // BASIC CRUD
    // =========================

    public List<Routine> getAll() {
        return repository.findAll();
    }

    public Routine getById(Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "Routine not found"));
    }

    public Routine create(Routine routine) {
        if (routine.getUser() != null && routine.getUser().getId() != null) {
            routine.setUser(loadUser(routine.getUser().getId()));
        }
        return repository.save(routine);
    }

    public Routine update(Long id, Routine routine) {
        Routine existing = getById(id);

        existing.setName(routine.getName());
        existing.setDescription(routine.getDescription());
        existing.setWeekStart(routine.getWeekStart());
        existing.setAutoGenerated(routine.isAutoGenerated());

        if (routine.getUser() != null && routine.getUser().getId() != null) {
            existing.setUser(loadUser(routine.getUser().getId()));
        }

        return repository.save(existing);
    }

    public void delete(Long id) {
        repository.delete(getById(id));
    }

    public List<Routine> getByUserId(Long userId) {
        return repository.findByUserIdOrderByWeekStartDesc(userId);
    }

    // =========================
    // GENERADOR DE RUTINA
    // =========================

    public Routine generateWeeklyPlan(Long userId, LocalDate weekStart) {

        if (weekStart == null) {
            throw new ResponseStatusException(BAD_REQUEST, "weekStart is required");
        }

        User user = loadUser(userId);

        int days = user.getTrainingDaysPerWeek();
        if (days < 1 || days > 7) {
            throw new ResponseStatusException(BAD_REQUEST, "trainingDaysPerWeek must be between 1 and 7");
        }
        if (user.getGoalType() == null) {
            throw new ResponseStatusException(BAD_REQUEST, "User goalType is required");
        }

        if (user.getLevel() == null) {
            throw new ResponseStatusException(BAD_REQUEST, "User level is required");
        }

        List<Exercise> availableExercises =
                exerciseRepository.findByOwnerIdIsNullOrSharedTrueOrOwnerId(userId);

        if (availableExercises.isEmpty()) {
            throw new ResponseStatusException(BAD_REQUEST, "No exercises available");
        }

        Routine routine = new Routine();
        routine.setName("Weekly plan " + weekStart);
        routine.setDescription("Auto-generated routine");
        routine.setWeekStart(weekStart);
        routine.setAutoGenerated(true);
        routine.setUser(user);

        List<Workout> workouts = new ArrayList<>();

        // =========================
        // DÍAS SEGÚN USUARIO
        // =========================

        int[] dayOffsets = buildDayOffsets(days);

        int exerciseIndex = 0;

        // =========================
        // CREACIÓN DE WORKOUTS
        // =========================

        for (int i = 0; i < dayOffsets.length; i++) {

            Workout workout = new Workout();
            workout.setDescription("Session " + (i + 1));
            workout.setUser(user);
            workout.setRoutine(routine);
            workout.setPlannedDate(weekStart.plusDays(dayOffsets[i]));

            List<WorkoutExercise> exercises = new ArrayList<>();

            for (int j = 0; j < 3; j++) {

                Exercise exercise = availableExercises.get(exerciseIndex % availableExercises.size());
                exerciseIndex++;

                exercises.add(buildWorkoutExercise(user, workout, exercise));
            }

            workout.setExercises(exercises);
            workouts.add(workout);
        }

        routine.setWorkouts(workouts);

        return repository.save(routine);
    }

    // =========================
    // EXERCISE BUILDER
    // =========================

    private WorkoutExercise buildWorkoutExercise(User user,
                                                 Workout workout,
                                                 Exercise exercise) {

        WorkoutExercise we = new WorkoutExercise();
        we.setWorkout(workout);
        we.setExercise(exercise);

        // ---- GOAL ----
        if ("gain_muscle".equals(user.getGoalType())) {
            we.setSets(4);
            we.setReps(10);
        } else if ("lose_weight".equals(user.getGoalType())) {
            we.setSets(3);
            we.setReps(15);
        } else {
            we.setSets(3);
            we.setReps(10);
        }

        // ---- LEVEL ----
        if ("beginner".equals(user.getLevel())) {
            we.setWeight(0);
        } else if ("intermediate".equals(user.getLevel())) {
            we.setWeight(20);
        } else {
            we.setWeight(40);
        }

        return we;
    }

    // =========================
    // USER LOAD
    // =========================

    private User loadUser(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "User not found"));
    }

    private int[] buildDayOffsets(int days) {
        int[] offsets = new int[days];

        if (days == 1) {
            offsets[0] = 0;
            return offsets;
        }

        for (int i = 0; i < days; i++) {
            offsets[i] = (int) Math.round((i * 6.0) / (days - 1));
        }

        return offsets;
    }
}
