package com.workoutplanner.backend.service;

import com.workoutplanner.backend.model.Exercise;
import com.workoutplanner.backend.model.Routine;
import com.workoutplanner.backend.model.User;
import com.workoutplanner.backend.model.Workout;
import com.workoutplanner.backend.model.WorkoutExercise;
import com.workoutplanner.backend.enums.GoalType;
import com.workoutplanner.backend.enums.Level;
import com.workoutplanner.backend.repository.ExerciseRepository;
import com.workoutplanner.backend.repository.RoutineRepository;
import com.workoutplanner.backend.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.NOT_FOUND;

@Service
public class RoutineService {

    private final RoutineRepository repository;
    private final UserRepository userRepository;
    private final ExerciseRepository exerciseRepository;

    public RoutineService(RoutineRepository repository,
                          UserRepository userRepository,
                          ExerciseRepository exerciseRepository) {
        this.repository = repository;
        this.userRepository = userRepository;
        this.exerciseRepository = exerciseRepository;
    }

    // =========================
    // BASIC CRUD
    // =========================

    public List<Routine> getAll() {
        return repository.findAll();
    }

    public Routine getById(Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "Routine not found"));
    }

    public Routine create(Routine routine) {
        if (routine.getUser() != null && routine.getUser().getId() != null) {
            routine.setUser(loadUser(routine.getUser().getId()));
        }
        return repository.save(routine);
    }

    public Routine update(Long id, Routine routine) {
        Routine existing = getById(id);

        existing.setName(routine.getName());
        existing.setDescription(routine.getDescription());
        existing.setWeekStart(routine.getWeekStart());
        existing.setAutoGenerated(routine.isAutoGenerated());

        if (routine.getUser() != null && routine.getUser().getId() != null) {
            existing.setUser(loadUser(routine.getUser().getId()));
        }

        return repository.save(existing);
    }

    public void delete(Long id) {
        repository.delete(getById(id));
    }

    public List<Routine> getByUserId(Long userId) {
        return repository.findByUserIdOrderByWeekStartDesc(userId);
    }

    // =========================
    // GENERADOR DE RUTINA
    // =========================

    @Transactional
    public Routine generateWeeklyPlan(Long userId, LocalDate weekStart) {

        if (weekStart == null) {
            throw new ResponseStatusException(BAD_REQUEST, "weekStart is required");
        }

        User user = loadUser(userId);

        int days = user.getTrainingDaysPerWeek();
        if (days < 1 || days > 7) {
            throw new ResponseStatusException(BAD_REQUEST, "trainingDaysPerWeek must be between 1 and 7");
        }
        if (user.getGoalType() == null) {
            throw new ResponseStatusException(BAD_REQUEST, "User goalType is required");
        }

        if (user.getLevel() == null) {
            throw new ResponseStatusException(BAD_REQUEST, "User level is required");
        }

        List<Exercise> availableExercises = deduplicateExercisesById(
                exerciseRepository.findByOwnerIdIsNullOrSharedTrueOrOwnerId(userId)
        );
        if (availableExercises.isEmpty()) {
            throw new ResponseStatusException(BAD_REQUEST, "No exercises available");
        }

        GoalType goalType = user.getGoalType();
        Level level = user.getLevel();

        Routine newRoutine = new Routine();
        newRoutine.setName("Weekly plan " + weekStart);
        newRoutine.setDescription("Auto-generated routine");
        newRoutine.setWeekStart(weekStart);
        newRoutine.setAutoGenerated(true);
        newRoutine.setUser(user);

        List<Workout> workouts = new ArrayList<>();
        Set<Long> weeklyUsedExercises = new HashSet<>();

        // =========================
        // DÍAS SEGÚN USUARIO
        // =========================

        int[] dayOffsets = buildDayOffsets(days);

        // =========================
        // CREACIÓN DE WORKOUTS
        // =========================

        for (int i = 0; i < dayOffsets.length; i++) {

            Workout workout = new Workout();
            workout.setDescription("Session " + (i + 1));
            workout.setUser(user);
            workout.setRoutine(newRoutine);
            workout.setPlannedDate(weekStart.plusDays(dayOffsets[i]));

            List<String> templateGroups = buildWorkoutTemplate(goalType, i);
            List<Exercise> selectedExercises = selectExercisesForWorkout(
                    availableExercises,
                    templateGroups,
                    goalType,
                    level,
                    weeklyUsedExercises,
                    goalType == GoalType.PERDER_PESO ? 4 : 3
            );

            List<WorkoutExercise> exercises = new ArrayList<>();
            for (Exercise exercise : selectedExercises) {
                exercises.add(buildWorkoutExercise(user, workout, exercise));
            }

            workout.setExercises(exercises);
            workouts.add(workout);
        }

        newRoutine.setWorkouts(workouts);

        // If there is already an auto-generated routine for this user and week, update it
        return repository.findByUserIdAndWeekStart(userId, weekStart)
                .map(existing -> {
                    // replace fields and workouts; using cascade + orphanRemoval will handle children
                    existing.setName(newRoutine.getName());
                    existing.setDescription(newRoutine.getDescription());
                    existing.setAutoGenerated(true);
                    existing.setWeekStart(newRoutine.getWeekStart());
                    // clear existing workouts and add new ones
                    existing.getWorkouts().clear();
                    existing.getWorkouts().addAll(newRoutine.getWorkouts());
                    return repository.save(existing);
                })
                .orElseGet(() -> repository.save(newRoutine));
    }

    // =========================
    // EXERCISE BUILDER
    // =========================

    private WorkoutExercise buildWorkoutExercise(User user,
                                                 Workout workout,
                                                 Exercise exercise) {

        WorkoutExercise we = new WorkoutExercise();
        we.setWorkout(workout);
        we.setExercise(exercise);

        // ---- GOAL ----
        switch (user.getGoalType()) {
            case GANAR_MUSCULO:
                we.setSets(4);
                we.setReps(8);
                break;

            case PERDER_PESO:
                we.setSets(3);
                we.setReps(12);
                break;

            case MANTENER_FORMA:
                we.setSets(3);
                we.setReps(10);
                break;
        }

        // ---- LEVEL ----
        switch (user.getLevel()) {
            case PRINCIPIANTE:
                we.setWeight(0);
                break;

            case INTERMEDIO:
                we.setWeight(20);
                break;

            case AVANZADO:
                we.setWeight(40);
                break;
        }

        return we;
    }

    // =========================
    // USER LOAD
    // =========================

    private User loadUser(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "User not found"));
    }

    private int[] buildDayOffsets(int days) {
        int[] offsets = new int[days];

        if (days == 1) {
            offsets[0] = 0;
            return offsets;
        }

        for (int i = 0; i < days; i++) {
            offsets[i] = (int) Math.round((i * 6.0) / (days - 1));
        }

        return offsets;
    }

    private List<String> buildWorkoutTemplate(GoalType goalType, int workoutIndex) {
        List<List<String>> templates = switch (goalType) {
            case GANAR_MUSCULO -> List.of(
                    List.of("CHEST", "SHOULDERS", "ARMS"),
                    List.of("BACK", "ARMS"),
                    List.of("LEGS", "CORE"),
                    List.of("CHEST", "BACK", "SHOULDERS"),
                    List.of("LEGS", "ARMS", "CORE")
            );
            case PERDER_PESO -> List.of(
                    List.of("FULL"),
                    List.of("CARDIO", "CORE", "LEGS"),
                    List.of("CARDIO", "FULL"),
                    List.of("CORE", "LEGS", "CARDIO")
            );
            case MANTENER_FORMA -> List.of(
                    List.of("FULL"),
                    List.of("CHEST", "BACK", "CORE"),
                    List.of("LEGS", "SHOULDERS"),
                    List.of("CARDIO", "CORE")
            );
        };

        return templates.get(workoutIndex % templates.size());
    }

    private List<Exercise> selectExercisesForWorkout(List<Exercise> availableExercises,
                                                     List<String> templateGroups,
                                                     GoalType goalType,
                                                     Level level,
                                                     Set<Long> weeklyUsedExercises,
                                                     int targetCount) {
        // Selección determinista evitando duplicados por ID.
        List<Exercise> selection = new ArrayList<>();
        Set<Long> selectedIds = new LinkedHashSet<>();
        List<Exercise> rankedAll = rankExercises(availableExercises, goalType, level);

        // 1) Intento por grupos: recorro rankedAll y cojo los que concuerden con cada grupo
        outer:
        for (String group : templateGroups) {
            for (Exercise candidate : rankedAll) {
                Long id = candidate.getId();
                if (id == null) continue;
                if (selectedIds.contains(id)) continue;  // Avoid duplicates in current workout
                if (!matchesGroup(candidate.getMuscleGroup(), group)) continue;
                if (weeklyUsedExercises != null && weeklyUsedExercises.contains(id)) continue;

                selection.add(candidate);
                selectedIds.add(id);
                if (weeklyUsedExercises != null) weeklyUsedExercises.add(id);

                if (selection.size() >= targetCount) break outer;
            }
        }

        // 2) Secondary pass: fill remaining slots without group matching
        for (Exercise candidate : rankedAll) {
            if (selection.size() >= targetCount) break;
            Long id = candidate.getId();
            if (id == null) continue;
            if (selectedIds.contains(id)) continue;  // Avoid duplicates in current workout
            if (weeklyUsedExercises != null && weeklyUsedExercises.contains(id)) continue;

            selection.add(candidate);
            selectedIds.add(id);
            if (weeklyUsedExercises != null) weeklyUsedExercises.add(id);
        }

        // 3) Fallback: if still not enough, allow repeating across days (but not same day)
        if (selection.size() < targetCount) {
            for (Exercise candidate : rankedAll) {
                if (selection.size() >= targetCount) break;
                Long id = candidate.getId();
                if (id == null) continue;
                if (selectedIds.contains(id)) continue;  // Never duplicate in same workout
                selection.add(candidate);
                selectedIds.add(id);
            }
        }

        return selection;
    }

    private List<Exercise> deduplicateExercisesById(List<Exercise> exercises) {
        if (exercises == null || exercises.isEmpty()) {
            return List.of();
        }

        List<Exercise> deduplicated = new ArrayList<>();
        Set<Long> seenIds = new LinkedHashSet<>();

        for (Exercise exercise : exercises) {
            if (exercise == null || exercise.getId() == null) {
                continue;
            }
            if (seenIds.add(exercise.getId())) {
                deduplicated.add(exercise);
            }
        }

        return deduplicated;
    }


    private List<Exercise> rankExercises(List<Exercise> exercises, GoalType goalType, Level level) {
        return exercises.stream()
                .sorted(Comparator
                        .comparingInt((Exercise exercise) -> exerciseScore(exercise, goalType, level))
                        .thenComparing(Exercise::getName, String.CASE_INSENSITIVE_ORDER))
                .toList();
    }

    private int exerciseScore(Exercise exercise, GoalType goalType, Level level) {
        int score = 0;

        if (goalType != null && exercise.getGoalType() != null && exercise.getGoalType() != goalType) {
            score += 100;
        }

        if (level != null) {
            if (exercise.getLevel() == null) {
                score += 10;
            } else {
                int diff = exercise.getLevel().ordinal() - level.ordinal();
                if (diff > 0) {
                    score += 40 + diff;
                } else {
                    score += Math.abs(diff);
                }
            }
        }

        return score;
    }


    private boolean matchesGroup(String actualGroup, String templateGroup) {
        String normalizedActual = normalizeGroup(actualGroup);
        String normalizedTemplate = normalizeGroup(templateGroup);

        return "FULL".equals(normalizedTemplate)
                || normalizedActual.equals(normalizedTemplate);
    }

    private String normalizeGroup(String muscleGroup) {
        if (muscleGroup == null) {
            return "";
        }

        return switch (muscleGroup.trim().toUpperCase()) {
            case "CHEST", "PECHO", "PECTORAL", "PECTORALES" -> "CHEST";
            case "BACK", "ESPALDA" -> "BACK";
            case "LEGS", "PIERNAS", "GLUTEOS", "GLÚTEOS" -> "LEGS";
            case "SHOULDERS", "HOMBRO", "HOMBROS" -> "SHOULDERS";
            case "ARMS", "ARM", "BRAZO", "BRAZOS", "BICEPS", "TRICEPS" -> "ARMS";
            case "CORE", "ABDOMEN", "ABS", "ABDOMINAL", "CINTURA" -> "CORE";
            case "CARDIO", "AEROBICO", "AERÓBICO" -> "CARDIO";
            default -> muscleGroup.trim().toUpperCase();
        };
    }

}
