package com.workoutplanner.backend.service;

import com.workoutplanner.backend.model.Exercise;
import com.workoutplanner.backend.model.Routine;
import com.workoutplanner.backend.model.User;
import com.workoutplanner.backend.model.Workout;
import com.workoutplanner.backend.model.WorkoutExercise;
import com.workoutplanner.backend.repository.ExerciseRepository;
import com.workoutplanner.backend.repository.RoutineRepository;
import com.workoutplanner.backend.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.ArrayList;
import static org.springframework.http.HttpStatus.NOT_FOUND;
import static org.springframework.http.HttpStatus.BAD_REQUEST;

import java.util.List;

@Service
public class RoutineService {

    private final RoutineRepository repository;
    private final UserRepository userRepository;
    private final ExerciseRepository exerciseRepository;

    public RoutineService(RoutineRepository repository,
                          UserRepository userRepository,
                          ExerciseRepository exerciseRepository) {
        this.repository = repository;
        this.userRepository = userRepository;
        this.exerciseRepository = exerciseRepository;
    }

    public List<Routine> getAll() {
        return repository.findAll();
    }

    public Routine getById(Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "Routine not found"));
    }

    public Routine create(Routine routine) {
        if (routine.getUser() != null && routine.getUser().getId() != null) {
            routine.setUser(loadUser(routine.getUser().getId()));
        }
        return repository.save(routine);
    }

    public Routine update(Long id, Routine routine) {
        Routine existing = getById(id);
        existing.setName(routine.getName());
        existing.setDescription(routine.getDescription());
        existing.setWeekStart(routine.getWeekStart());
        existing.setAutoGenerated(routine.isAutoGenerated());
        if (routine.getUser() != null && routine.getUser().getId() != null) {
            existing.setUser(loadUser(routine.getUser().getId()));
        }
        return repository.save(existing);
    }

    public void delete(Long id) {
        Routine routine = getById(id);
        repository.delete(routine);
    }

    public List<Routine> getByUserId(Long userId) {
        return repository.findByUserIdOrderByWeekStartDesc(userId);
    }

    public Routine generateWeeklyPlan(Long userId, LocalDate weekStart) {
        if (weekStart == null) {
            throw new ResponseStatusException(BAD_REQUEST, "weekStart is required");
        }

        User user = loadUser(userId);
        List<Exercise> availableExercises = exerciseRepository.findByOwnerIdIsNullOrSharedTrueOrOwnerId(userId);
        if (availableExercises.isEmpty()) {
            throw new ResponseStatusException(BAD_REQUEST, "No exercises available to generate plan");
        }

        Routine routine = new Routine();
        routine.setName("Weekly plan " + weekStart);
        routine.setDescription("Auto-generated weekly routine");
        routine.setWeekStart(weekStart);
        routine.setAutoGenerated(true);
        routine.setUser(user);

        List<Workout> workouts = new ArrayList<>();
        int[] dayOffsets = {0, 2, 4, 6};
        int exerciseIndex = 0;

        for (int dayOffset : dayOffsets) {
            Workout workout = new Workout();
            workout.setDescription("Session " + (workouts.size() + 1));
            workout.setUser(user);
            workout.setRoutine(routine);
            workout.setPlannedDate(weekStart.plusDays(dayOffset));

            List<WorkoutExercise> workoutExercises = new ArrayList<>();
            for (int i = 0; i < 3; i++) {
                Exercise selectedExercise = availableExercises.get(exerciseIndex % availableExercises.size());
                exerciseIndex++;

                WorkoutExercise workoutExercise = new WorkoutExercise();
                workoutExercise.setWorkout(workout);
                workoutExercise.setExercise(selectedExercise);
                workoutExercise.setSets(3);
                workoutExercise.setReps(10);
                workoutExercise.setWeight(0);
                workoutExercises.add(workoutExercise);
            }

            workout.setExercises(workoutExercises);
            workouts.add(workout);
        }

        routine.setWorkouts(workouts);
        return repository.save(routine);
    }

    private User loadUser(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, "User not found"));
    }
}
